#ifndef CONFIG_H
#define CONFIG_H

// WIFI_CONFIG
#define WIFI_DEFAULT_PASSWORD "1234567890"
#define WIFI_SSID       "FES_Device"
#define WIFI_CHANNEL    1
#define WIFI_MAX_CONN   1
#define WIFI_PASSWORD_MIN_LENGTH 8
#define WIFI_PASSWORD_MAX_LENGTH 63

// TCP_CONFIG
#define TCP_SERVER_PORT 5000

// GET_INFO
#define DEVICE_INFO_PAYLOAD_SIZE 6
#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 0
#define PROTOCOL_VERSION_MAJOR 1
#define PROTOCOL_VERSION_MINOR 0
#define PROTOCOL_VERSION_PATCH 0

#define PROTOCOL_SIGNATURE 0xAA55
#define PROTOCOL_MAX_PAYLOAD_SIZE 256

#endif
