#ifndef CONFIG_H
#define CONFIG_H

// COMMANDS
#define CMD_GET_INFO 0x01
#define CMD_SET_WIFI_PASSWORD 0x02

// WIFI_CONFIG
#define WIFI_DEFAULT_PASSWORD "1234567890"
#define WIFI_SSID       "FES_Device"
#define WIFI_CHANNEL    1
#define WIFI_MAX_CONN   4
#define WIFI_PASSWORD_MIN_LENGTH 8
#define WIFI_PASSWORD_MAX_LENGTH 63

// TCP_CONFIG
#define TCP_SERVER_PORT 5000
#define TCP_BUFFER_SIZE 256

// GET_INFO
#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 0
#define PROTOCOL_VERSION_MAJOR 1
#define PROTOCOL_VERSION_MINOR 0
#define PROTOCOL_VERSION_PATCH 0

#endif
